### ISSUE TITLE
Publish first production dataset

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#21]
@sarahcd @timrobertson100 I now have an operational function to create Darwin Core from a Movebank dataset: https://inbo.github.io/movepub/reference/write_dwc.html

I have used it to create:

- IPT: https://ipt.gbif.org/resource?r=o_westerschelde
- GBIF: https://www.gbif-uat.org/dataset/0ef15f32-b41d-4274-ae96-eb5d0059fee6

I now want to use this to create the first production dataset, but would like some feedback on:

- [x] Is there sufficient metadata? See https://github.com/inbo/movepub/issues/9
- [x] Are we ok with the structure of the data? See also last remark at https://github.com/inbo/movepub/issues/7
- [x] What DOI to assign: #15

**Comment by MortenHofft** [comment]
**About events in the UI**

The way we handle Events does not work very well with this. We do not model Events. So to show Events we look at occurrences and the distinct EventIDs. And then use the first occurrence within each for the event metadata.

So e.g. https://www.gbif-uat.org/dataset/0ef15f32-b41d-4274-ae96-eb5d0059fee6/event/14256071453
`Sampling protocol gps` comes from the first matching occurrence for that Event.

**No metadata for parent events**
That also means that Events without occurrences will not appear at all or will have no metadata. E.g. 
https://www.gbif-uat.org/dataset/0ef15f32-b41d-4274-ae96-eb5d0059fee6/parentevent/L918401_5742
Since it is a parentEvent without occurrences, then we cannot say much about it (in this specific case we can summarize taxonomy since the occurrences directly mention the EventId as the parentEventId)

We could try to have a fallback and look for the first occurrence with that `parentEventId` and use that information instead?

**Comment by MortenHofft** [comment]
Are there anything special that we ought to show for these types of datasets? (ignoring for now how we detect that it is a tracking dataset).

Like the list of distinct `organismIDs` or something else?

**Comment by peterdesmet** [comment]
> The way we handle Events does not work very well with this. We do not model Events. So to show Events we look at occurrences and the distinct EventIDs. And then use the first occurrence within each for the event metadata.

Yeah, the approach worked well when all occurrences (1 HumanObservation, many MachineObservations) shared the same "deployment" event ID. I really liked how it was visualized then.

We gave all occurrences their own event ID to align more with the event centered approach of the Grand Unified Model. I guess the GBIF UI will undergo changes to represent that meaningfully, but can I already suggest dataset pages to show top level parents (only), which the user can drill down in?

For GPS tracking datasets specifically, indicating the **number of distinct individuals** would be useful. If you want to go advanced, a chart with time (x) and deployment (y) could be useful. Something like:

<img width="558" alt="Screenshot 2022-05-11 at 14 03 23" src="https://user-images.githubusercontent.com/600993/167845620-d35c3345-d9f5-4338-958d-b31e5aac3832.png">

**Comment by peterdesmet** [comment]
First production dataset published at https://www.gbif.org/dataset/20bbd36e-d1a1-4169-8663-59feaa2641c0

**Comment by peterdesmet** [comment]
Note to self: once `O_ASSEN` is published, reference to it from documentation.

**Comment by sarahcd** [comment]
fantastic job!

**Comment by peterdesmet** [comment]
List of datasets is growing: https://www.gbif.org/dataset/search?q=movebank&publishing_org=1cd669d0-80ea-11de-a9d0-f1765f95f18b

O_ASSEN is referenced in the vignette.

Closing issue
